events {}

http {
    # redirect HTTP ke HTTPS
    server {
        listen 80;
        server_name purrduli.tech api.purrduli.tech stream.purrduli.tech;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # frontend
    server {
        listen 443 ssl;
        server_name purrduli.tech;

        ssl_certificate /etc/letsencrypt/live/purrduli.tech/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/purrduli.tech/privkey.pem;

        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # backend API
    server {
        listen 443 ssl;
        server_name api.purrduli.tech;

        ssl_certificate /etc/letsencrypt/live/purrduli.tech/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/purrduli.tech/privkey.pem;

        location / {
            proxy_pass http://backend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            # WebSocket support (untuk realtime)
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }

    # mediamtx HLS & WebRTC
    server {
        listen 443 ssl;
        server_name stream.purrduli.tech;

        ssl_certificate /etc/letsencrypt/live/purrduli.tech/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/purrduli.tech/privkey.pem;

        location / {
            proxy_pass http://mediamtx:8888;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
